# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{albacore}
  s.version = "0.2.0.preview2"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Derick Bailey", "Ben Hall", "Steve Harman", "etc"]
  s.date = %q{2010-08-01}
  s.description = %q{Easily build your .NET solutions with Ruby and Rake, using this suite of Rake tasks.}
  s.email = %q{derickbailey@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".autotest",
     "EULA.txt",
     "README.markdown",
     "VERSION",
     "install_dependencies.rb",
     "lib/albacore.rb",
     "lib/albacore/albacoremodel.rb",
     "lib/albacore/assemblyinfo.rb",
     "lib/albacore/assemblyinfolanguages/csharpengine.rb",
     "lib/albacore/assemblyinfolanguages/vbnetengine.rb",
     "lib/albacore/config/assemblyinfoconfig.rb",
     "lib/albacore/config/config.rb",
     "lib/albacore/config/cscconfig.rb",
     "lib/albacore/config/docuconfig.rb",
     "lib/albacore/config/execconfig.rb",
     "lib/albacore/config/msbuildconfig.rb",
     "lib/albacore/config/mspecconfig.rb",
     "lib/albacore/config/nantconfig.rb",
     "lib/albacore/config/ncoverconsoleconfig.rb",
     "lib/albacore/config/ncoverreportconfig.rb",
     "lib/albacore/config/ndependconfig.rb",
     "lib/albacore/config/netversion.rb",
     "lib/albacore/config/nunitconfig.rb",
     "lib/albacore/config/specflowreportconfig.rb",
     "lib/albacore/config/sqlcmdconfig.rb",
     "lib/albacore/config/unzipconfig.rb",
     "lib/albacore/config/xbuildconfig.rb",
     "lib/albacore/config/xunitconfig.rb",
     "lib/albacore/config/zipconfig.rb",
     "lib/albacore/csc.rb",
     "lib/albacore/docu.rb",
     "lib/albacore/exec.rb",
     "lib/albacore/msbuild.rb",
     "lib/albacore/mspectestrunner.rb",
     "lib/albacore/nant.rb",
     "lib/albacore/ncoverconsole.rb",
     "lib/albacore/ncoverreport.rb",
     "lib/albacore/ncoverreports/assemblyfilter.rb",
     "lib/albacore/ncoverreports/branchcoverage.rb",
     "lib/albacore/ncoverreports/classfilter.rb",
     "lib/albacore/ncoverreports/codecoveragebase.rb",
     "lib/albacore/ncoverreports/cyclomaticcomplexity.rb",
     "lib/albacore/ncoverreports/documentfilter.rb",
     "lib/albacore/ncoverreports/fullcoveragereport.rb",
     "lib/albacore/ncoverreports/methodcoverage.rb",
     "lib/albacore/ncoverreports/methodfilter.rb",
     "lib/albacore/ncoverreports/namespacefilter.rb",
     "lib/albacore/ncoverreports/reportfilterbase.rb",
     "lib/albacore/ncoverreports/summaryreport.rb",
     "lib/albacore/ncoverreports/symbolcoverage.rb",
     "lib/albacore/ndepend.rb",
     "lib/albacore/nunittestrunner.rb",
     "lib/albacore/specflowreport.rb",
     "lib/albacore/sqlcmd.rb",
     "lib/albacore/support/attrmethods.rb",
     "lib/albacore/support/failure.rb",
     "lib/albacore/support/logging.rb",
     "lib/albacore/support/openstruct.rb",
     "lib/albacore/support/runcommand.rb",
     "lib/albacore/support/supportlinux.rb",
     "lib/albacore/support/yamlconfig.rb",
     "lib/albacore/unzip.rb",
     "lib/albacore/xbuild.rb",
     "lib/albacore/xunittestrunner.rb",
     "lib/albacore/zipdirectory.rb",
     "lib/rake/assemblyinfotask.rb",
     "lib/rake/csctask.rb",
     "lib/rake/docutask.rb",
     "lib/rake/exectask.rb",
     "lib/rake/msbuildtask.rb",
     "lib/rake/mspectask.rb",
     "lib/rake/nanttask.rb",
     "lib/rake/ncoverconsoletask.rb",
     "lib/rake/ncoverreporttask.rb",
     "lib/rake/ndependtask.rb",
     "lib/rake/nunittask.rb",
     "lib/rake/specflowreporttask.rb",
     "lib/rake/sqlcmdtask.rb",
     "lib/rake/support/createtask.rb",
     "lib/rake/unziptask.rb",
     "lib/rake/xbuildtask.rb",
     "lib/rake/xunittask.rb",
     "lib/rake/ziptask.rb",
     "rakefile.rb",
     "watchrtesting.rb",
     "yaml_autoconfig_test.yml"
  ]
  s.homepage = %q{http://albacorebuild.net}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Dolphin-Safe Rake Tasks For .NET Systems}
  s.test_files = [
    "spec/albacoremodel_spec.rb",
     "spec/assemblyinfotask_spec.rb",
     "spec/assemblyinfo_spec.rb",
     "spec/attrmethods_spec.rb",
     "spec/config_spec.rb",
     "spec/createtask_spec.rb",
     "spec/csctask_spec.rb",
     "spec/csc_spec.rb",
     "spec/docutask_spec.rb",
     "spec/docu_spec.rb",
     "spec/exectask_spec.rb",
     "spec/exec_spec.rb",
     "spec/msbuildtask_spec.rb",
     "spec/msbuild_spec.rb",
     "spec/mspectask_spec.rb",
     "spec/mspec_spec.rb",
     "spec/nanttask_spec.rb",
     "spec/nant_spec.rb",
     "spec/ncoverconsoletask_spec.rb",
     "spec/ncoverconsole_spec.rb",
     "spec/ncoverreporttask_spec.rb",
     "spec/ncoverreport_spec.rb",
     "spec/ndependtask_spec.rb",
     "spec/ndepend_spec.rb",
     "spec/nunittask_spec.rb",
     "spec/nunittestrunner_spec.rb",
     "spec/patches/docu_patch.rb",
     "spec/patches/fail_patch.rb",
     "spec/patches/system_patch.rb",
     "spec/runcommand_spec.rb",
     "spec/specflowreporttask_spec.rb",
     "spec/specflowreport_spec.rb",
     "spec/sqlcmdtask_spec.rb",
     "spec/sqlcmd_spec.rb",
     "spec/support/assemblyinfotester.rb",
     "spec/support/msbuildtestdata.rb",
     "spec/support/nanttestdata.rb",
     "spec/support/ncoverconsoletestdata.rb",
     "spec/support/ncoverreporttestdata.rb",
     "spec/support/spec_helper.rb",
     "spec/support/ziptestdata.rb",
     "spec/unzip_spec.rb",
     "spec/xbuild_spec.rb",
     "spec/xunittask_spec.rb",
     "spec/xunit_spec.rb",
     "spec/yamlconfig_spec.rb",
     "spec/ziptask_spec.rb",
     "spec/zip_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0.8.7"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0.9.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_development_dependency(%q<derickbailey-notamock>, [">= 0.0.1"])
      s.add_development_dependency(%q<jekyll>, [">= 0.5.7"])
      s.add_development_dependency(%q<watchr>, [">= 0.6"])
    else
      s.add_dependency(%q<rake>, [">= 0.8.7"])
      s.add_dependency(%q<rubyzip>, [">= 0.9.4"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_dependency(%q<derickbailey-notamock>, [">= 0.0.1"])
      s.add_dependency(%q<jekyll>, [">= 0.5.7"])
      s.add_dependency(%q<watchr>, [">= 0.6"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0.8.7"])
    s.add_dependency(%q<rubyzip>, [">= 0.9.4"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<jeweler>, [">= 1.4.0"])
    s.add_dependency(%q<derickbailey-notamock>, [">= 0.0.1"])
    s.add_dependency(%q<jekyll>, [">= 0.5.7"])
    s.add_dependency(%q<watchr>, [">= 0.6"])
  end
end

