# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Albacore}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Derick Bailey"]
  s.date = %q{2009-10-05}
  s.description = %q{Easily build your .NET solutions with rake, using this suite of custom tasks.}
  s.email = %q{derickbailey@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "EULA.txt",
     "README.markdown",
     "VERSION",
     "lib/albacore.rb",
     "lib/albacore/assemblyinfo.rb",
     "lib/albacore/msbuild.rb",
     "lib/albacore/ncoverconsole.rb",
     "lib/albacore/nunittestrunner.rb",
     "lib/albacore/patches/buildparameters.rb",
     "lib/albacore/sqlcmd.rb",
     "lib/albacore/support/albacorebase.rb",
     "lib/albacore/support/logging.rb",
     "lib/rake/assemblyinfotask.rb",
     "lib/rake/msbuildtask.rb",
     "lib/rake/ncoverconsoletask.rb",
     "lib/rake/sqlcmdtask.rb",
     "lib/spec/albacorebase_spec.rb",
     "lib/spec/assemblyinfo_spec.rb",
     "lib/spec/assemblyinfotask_spec.rb",
     "lib/spec/msbuild_spec.rb",
     "lib/spec/msbuildtask_spec.rb",
     "lib/spec/ncoverconsole_spec.rb",
     "lib/spec/ncoverconsoletask_spec.rb",
     "lib/spec/patches/system_patch.rb",
     "lib/spec/patches/tasklib_patch.rb",
     "lib/spec/sqlcmd_spec.rb",
     "lib/spec/sqlcmdtask_spec.rb",
     "lib/spec/support/AssemblyInfo/AssemblyInfo.cs",
     "lib/spec/support/CodeCoverage/TestResult.xml",
     "lib/spec/support/CodeCoverage/assemblies/TestSolution.Tests.dll",
     "lib/spec/support/CodeCoverage/assemblies/TestSolution.dll",
     "lib/spec/support/CodeCoverage/assemblies/nunit.framework.dll",
     "lib/spec/support/CodeCoverage/failing_assemblies/TestSolution.FailingTests.dll",
     "lib/spec/support/CodeCoverage/failing_assemblies/nunit.framework.dll",
     "lib/spec/support/TestSolution/TestSolution.FailingTests/FailingTestFixture.cs",
     "lib/spec/support/TestSolution/TestSolution.FailingTests/Properties/AssemblyInfo.cs",
     "lib/spec/support/TestSolution/TestSolution.FailingTests/TestSolution.FailingTests.csproj",
     "lib/spec/support/TestSolution/TestSolution.Tests/Properties/AssemblyInfo.cs",
     "lib/spec/support/TestSolution/TestSolution.Tests/SomeTestFixture.cs",
     "lib/spec/support/TestSolution/TestSolution.Tests/TestSolution.Tests.csproj",
     "lib/spec/support/TestSolution/TestSolution.sln",
     "lib/spec/support/TestSolution/TestSolution/Class1.cs",
     "lib/spec/support/TestSolution/TestSolution/Properties/AssemblyInfo.cs",
     "lib/spec/support/TestSolution/TestSolution/TestSolution.csproj",
     "lib/spec/support/Tools/NCover-v3.2/ActiproEULA.hml",
     "lib/spec/support/Tools/NCover-v3.2/ActiproSoftware.CodeHighlighter.Net20.dll",
     "lib/spec/support/Tools/NCover-v3.2/ActiproSoftware.Shared.Net20.dll",
     "lib/spec/support/Tools/NCover-v3.2/AdminBootstrapper.exe",
     "lib/spec/support/Tools/NCover-v3.2/MSVCM90.dll",
     "lib/spec/support/Tools/NCover-v3.2/MSVCP90.dll",
     "lib/spec/support/Tools/NCover-v3.2/MSVCR90.dll",
     "lib/spec/support/Tools/NCover-v3.2/Microsoft.VC90.CRT.manifest",
     "lib/spec/support/Tools/NCover-v3.2/Mindscape.LightSpeed.Linq.dll",
     "lib/spec/support/Tools/NCover-v3.2/Mindscape.LightSpeed.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Console.exe",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Console.exe.config",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Data.x86.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Explorer.Framework.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Explorer.exe",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Explorer.exe.config",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Framework.XmlSerializers.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Framework.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Interfaces.Core.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Interfaces.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Legacy.Configuration.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Lib.x86.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Registration.exe",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Reporting.exe",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Runner.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCover.UpConvert.exe",
     "lib/spec/support/Tools/NCover-v3.2/NCover.Utilities.dll",
     "lib/spec/support/Tools/NCover-v3.2/NCoverEULA.pdf",
     "lib/spec/support/Tools/NCover-v3.2/NCoverExplorer.Console.exe",
     "lib/spec/support/Tools/NCover-v3.2/ReportingExample.config",
     "lib/spec/support/Tools/NCover-v3.2/System.Data.SQLite.dll",
     "lib/spec/support/Tools/NUnit-v2.5/NUnitFitTests.html",
     "lib/spec/support/Tools/NUnit-v2.5/NUnitTests.config",
     "lib/spec/support/Tools/NUnit-v2.5/NUnitTests.nunit",
     "lib/spec/support/Tools/NUnit-v2.5/TestResult.xml",
     "lib/spec/support/Tools/NUnit-v2.5/agent.conf",
     "lib/spec/support/Tools/NUnit-v2.5/agent.log.conf",
     "lib/spec/support/Tools/NUnit-v2.5/clr.bat",
     "lib/spec/support/Tools/NUnit-v2.5/framework/nunit.framework.dll",
     "lib/spec/support/Tools/NUnit-v2.5/framework/nunit.framework.xml",
     "lib/spec/support/Tools/NUnit-v2.5/framework/nunit.mocks.dll",
     "lib/spec/support/Tools/NUnit-v2.5/framework/pnunit.framework.dll",
     "lib/spec/support/Tools/NUnit-v2.5/launcher.log.conf",
     "lib/spec/support/Tools/NUnit-v2.5/lib/Failure.png",
     "lib/spec/support/Tools/NUnit-v2.5/lib/Ignored.png",
     "lib/spec/support/Tools/NUnit-v2.5/lib/Inconclusive.png",
     "lib/spec/support/Tools/NUnit-v2.5/lib/Skipped.png",
     "lib/spec/support/Tools/NUnit-v2.5/lib/Success.png",
     "lib/spec/support/Tools/NUnit-v2.5/lib/fit.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/log4net.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit-console-runner.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit-gui-runner.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit.core.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit.core.interfaces.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit.fixtures.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit.uiexception.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit.uikit.dll",
     "lib/spec/support/Tools/NUnit-v2.5/lib/nunit.util.dll",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-agent.exe",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-agent.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-console-x86.exe",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-console-x86.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-console.exe",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-console.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-x86.exe",
     "lib/spec/support/Tools/NUnit-v2.5/nunit-x86.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/nunit.exe",
     "lib/spec/support/Tools/NUnit-v2.5/nunit.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/nunit.framework.dll",
     "lib/spec/support/Tools/NUnit-v2.5/pnunit-agent.exe",
     "lib/spec/support/Tools/NUnit-v2.5/pnunit-agent.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/pnunit-launcher.exe",
     "lib/spec/support/Tools/NUnit-v2.5/pnunit-launcher.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/pnunit.framework.dll",
     "lib/spec/support/Tools/NUnit-v2.5/pnunit.tests.dll",
     "lib/spec/support/Tools/NUnit-v2.5/runFile.exe",
     "lib/spec/support/Tools/NUnit-v2.5/runFile.exe.config",
     "lib/spec/support/Tools/NUnit-v2.5/runpnunit.bat",
     "lib/spec/support/Tools/NUnit-v2.5/test.conf",
     "lib/spec/support/assemblyinfotester.rb",
     "lib/spec/support/msbuildtestdata.rb",
     "lib/spec/support/spec_helper.rb",
     "lib/spec/support/sqlcmd.yml",
     "rakefile.rb"
  ]
  s.homepage = %q{http://github.com/derickbailey/Albacore}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Suite of Rake Build Tasks For .Net Solutions}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
