require File.join(File.dirname(__FILE__), 'albacore', 'msbuild')
require File.join(File.dirname(__FILE__), 'albacore', 'assemblyinfo')
require File.join(File.dirname(__FILE__), 'albacore', 'support', 'logging')
require File.join(File.dirname(__FILE__), 'rake', 'msbuildtask')
require File.join(File.dirname(__FILE__), 'rake', 'assemblyinfotask')
